import React, { useEffect, useState } from "react";
import { Modal, Button } from "react-bootstrap";
import "bootstrap/dist/css/bootstrap.min.css";
import { empty, isEmpty, jQuery, showToast } from "utils/GlobalFunctions";

function TwoFactorCodeModal(props) {
  const { isVisible, setShowconfirmModal, submitModalData, modalClass, onCancelModal } = props;
  useEffect(() => {
    if (isVisible !== undefined) {
      setShow(isVisible);
      if (isVisible) {
        setTimeout(function () {
          jQuery(".verification-code-item-0").focus();
        }, 300);
      }
    }
  }, [isVisible]);
  const [show, setShow] = useState(false);
  const [codeData, setCodeData] = useState([]);
  const [errorField, setErrorField] = useState([]);
  const validateFields = () => {
    var errorList = Array();
    for (var i = 0; i < 6; i++) {
      errorList = isEmpty(codeData, i, errorList);
    }
    setErrorField([...errorList]);
    return errorList.length > 0 ? false : true;
  };

  const handleClose = () => {
    setShow(false);
    setShowconfirmModal(false);
    if(!empty(onCancelModal)){
      onCancelModal()
    }
  };

  const rows = [0, 1, 2, 3, 4, 5].map((val, index) => {
    return (
      <input
        key={index}
        className={`verification-code-item no-spin verification-code-item-${index}`}
        type="number"
        maxLength="1"
        size="1"
        min="0"
        max="9"
        pattern="[0-9]{1}"
        onChange={(e) => {
          onChangeCodeItemField(e, index);
        }}
        onKeyPress={(e) => {
          onKeyPressed(e);
        }}
      />
    );
  });

  const onChangeCodeItemField = (e, field_index) => {
    let val = e.target.value;
    let code = "";
    if(val.length > 0) {
        code = val.substr(val.length - 1); 
    }
    codeData[field_index] = code;
    setCodeData({ ...codeData });
  };

  const submitVerificationCode = () => {
    let is_valid = validateFields();
    console.log("is valid", is_valid);
    if (is_valid) {
        submitModalData(codeData);
    }else {
        showToast("Please input 2-step verification code correctly", "error");
    }
  };

  const onKeyPressed = (e) => {
    if(e.key === 'Enter'){
      console.log('enter press here!');
      submitVerificationCode()
    }
  };
  return (
    <>
      <Modal
        show={show}
        onHide={handleClose}
        backdrop="static"
        keyboard={false}
        centered
        dialogClassName={modalClass}
      >
        <Modal.Header closeButton>
          <Modal.Title>Google 2-Step Verification</Modal.Title>
        </Modal.Header>
        <Modal.Body>
          <div className="block">
            <p className="text-normal margin-bottom-20 text-gray modal-header-desc">
              Enter the 6-digit code generated by your authenticator app.
            </p>
          </div>
          <div className="block margin-bottom-20 text-center">
            <div className="sms-verification-box six-digits-box">
              <div id="dialog">
                <div id="form" className="verification-form">
                  {rows}
                </div>
              </div>
            </div>
          </div>
          <div className="block">
            <p className="margin-bottom-10 modal-footer-desc">
              If you have trouble signing in, please contact our support!
            </p>
          </div>
        </Modal.Body>
        <Modal.Footer>
        <button
            type="button"
            className="btn btn-light btn-cancel-2fa mr-1"
            data-dismiss="modal"
            onClick={handleClose}
          >
            Cancel
          </button>
          <button
            type="button"
            className="btn-complete-2fa btn btn-green btn-primary"
            onClick={submitVerificationCode}
          >
            Continue
          </button>
        </Modal.Footer>
      </Modal>
    </>
  );
}

export default TwoFactorCodeModal;
