import {
  ROUTE_LOGIN,
  ROUTE_USER_ACADEMY,
  ROUTE_USER_AFFILIATE,
  ROUTE_USER_CHART,
  ROUTE_USER_DASHBOARD,
  ROUTE_USER_FEED,
  ROUTE_USER_LICENSE,
  ROUTE_USER_LOGOUT,
  ROUTE_USER_MARKETING,
  ROUTE_USER_PAYMENT,
  ROUTE_USER_PROFILE,
  ROUTE_USER_SOFTWARE,
  ROUTE_USER_SUPPORT,
  ROUTE_USER_TEAM,
  ROUTE_USER_TICKET,
  ROUTE_USER_VERIFICATION,
  ROUTE_USER_VPS,
  ROUTE_USER_WALLET,
  USER_LEVEL_AFFILIATE,
  USER_LEVEL_ALL,
  USER_LEVEL_CUSTOMER,
} from "navigation/CONSTANTS";


export const USER_MENU_ITEMS = [
  {
    route: ROUTE_USER_FEED,
    icon: "mdi mdi-rss-box",
    title: "What's new",
    level: USER_LEVEL_ALL,
  },
  {
    route: ROUTE_USER_SOFTWARE,
    icon: "mdi mdi-hand-pointing-right",
    title: "Getting Started",
    level: USER_LEVEL_ALL,
  },
  {
    route: ROUTE_USER_DASHBOARD,
    icon: "mdi mdi-home",
    title: "Dashboard",
    level: USER_LEVEL_ALL,
  },
  {
    route: ROUTE_USER_VPS,
    icon: "mdi mdi-server-plus",
    title: "Virtual Private Server",
    level: USER_LEVEL_ALL,
  },
  {
    route: ROUTE_USER_TEAM,
    icon: "mdi mdi-sitemap",
    title: "My Team",
    level: USER_LEVEL_AFFILIATE,
  },
  {
    route: ROUTE_USER_LICENSE,
    icon: "mdi mdi-format-list-bulleted-type",
    title: "Membership",
    level: USER_LEVEL_ALL,
  },
  {
    route: ROUTE_USER_ACADEMY,
    icon: "mdi mdi-near-me",
    title: "Higher Level Academy",
    level: USER_LEVEL_ALL,
  },
  {
    route: ROUTE_USER_MARKETING,
    icon: "mdi mdi-monitor",
    title: "Affiliate Only Section",
    level: USER_LEVEL_AFFILIATE,
  },
  // {
  //   route: ROUTE_USER_CHART,
  //   icon: "mdi mdi-chart-line",
  //   title: "Live Charts",
  //   level: USER_LEVEL_ALL,
  // },
  {
    route: ROUTE_USER_WALLET,
    icon: "mdi mdi-wallet",
    title: "Wallet",
    level: USER_LEVEL_ALL,
  },
  {
    route: ROUTE_USER_AFFILIATE,
    icon: "mdi mdi-account-convert",
    title: "Become an Affiliate",
    level: USER_LEVEL_CUSTOMER,
  },
  {
    route: ROUTE_USER_PAYMENT,
    icon: "mdi mdi-currency-usd",
    title: "Payments",
    level: USER_LEVEL_ALL,
  },
  {
    route: ROUTE_USER_TICKET,
    icon: "mdi mdi-forum",
    title: "Support Tickets",
    level: USER_LEVEL_ALL,
  },
  {
    route: ROUTE_USER_SUPPORT,
    icon: "mdi mdi-help-circle",
    title: "FAQ",
    level: USER_LEVEL_ALL,
  },
  {
    route: ROUTE_USER_VERIFICATION,
    icon: "mdi mdi-lock",
    title: "Two-Step Verification",
    level: USER_LEVEL_ALL,
  },
  {
    route: ROUTE_USER_PROFILE,
    icon: "mdi mdi-account",
    title: "Profile / Cancellation",
    level: USER_LEVEL_ALL,
  },
];
